const router = require('express').Router()
const authController = require('./auth.controller')
const petitionType = require('./petitionType')
const petitionStatus = require('./petitionStatus')
const users = require('./users')
const petition = require('./petition')
const news = require("./news")
const uploadFile = require("./uploadFile")
const studentUnion = require("./studentUnion")
const newsType = require("./newsType")
const position = require("./position")
const studentUnionInfo = require("./studentUnionInfo")
const activityTypes = require("./activityTypes")
const voteResult = require("./votingResults")
const voting = require("./voting")
const formInfo = require("./formInfo")
const projectApproved = require("./projectApproved")
const requestApproved = require("./requestApprove")

router.use(authController)
router.use(petitionType)
router.use(petitionStatus)
router.use(users)
router.use(petition)
router.use(news)
router.use(uploadFile)
router.use(studentUnion)
router.use(newsType)
router.use(position)
router.use(studentUnionInfo)
router.use(activityTypes)
router.use(voteResult)
router.use(voting)
router.use(formInfo)
router.use(projectApproved)
router.use(requestApproved)

router.get("/", (req, res) => {
    return res.send({ api: "SAMOSIT" })
})

router.get("/health", (req, res) => {
    return res.send({ status: "healthy" })
})

// export router
module.exports = router
