name: CI_CD SMOSIT_BACKEND

on:
  push:
    branches: [main] 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2     

      - name: Login to Github Container Registy
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.ACCOUNT }}  
          password: ${{ secrets.TOKEN_GITHUB }} 

      - name : Create env file
        run : |
            touch .env
            echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
            echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
            echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
            echo REDIRECT_URI=${{ secrets.REDIRECT_URI }} >> .env
            ls -a
            cat .env

      - name: Build Docker image
        run: |
           docker build . --tag ghcr.io/ppitchanon/smosit-backend:latest
           docker images

      - name: Push Docker image to Github Container registry
        run: |
          docker push ghcr.io/ppitchanon/smosit-backend:latest

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - name: Login ssh to remote server and deploy container 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker ps
            docker rm -f backend 
            docker pull ghcr.io/ppitchanon/smosit-backend:latest 
            docker images
            docker-compose up -d backend
            docker image prune -f 
            docker ps -a 
